// AUTO-GENERATED from data/web/drug_map.csv by scripts/gen_drugs_ts.py — do not edit by hand.
// 49 branded drugs + metformin control.
export const DRUGS = [
  "Vraylar", "Dupixent", "Rinvoq", "Jardiance", "Mounjaro", "Skyrizi", "Rexulti", "Ozempic", "Tremfya", "Ubrelvy", "Qulipta", "Airsupra", "Nurtec", "Trelegy", "Otezla", "Farxiga", "Caplyta", "Eliquis", "Wegovy", "Botox", "Kerendia", "Xifaxan", "Veozah", "Ingrezza", "Rybelsus", "Voquezna", "Austedo", "Cosentyx", "Xarelto", "Repatha", "Breztri", "Evenity", "Linzess", "Auvelity", "Taltz", "Entresto", "Nucala", "Aristada", "Gemtesa", "Zoryve", "Opzelura", "Creon", "Abilify", "Tezspire", "Spravato", "Xeljanz", "Stelara", "Invega", "Uzedy", "Metformin",
] as const;
export type DrugKey = (typeof DRUGS)[number];

export const DRUG_META: Record<string, { label: string; generic: string; control?: boolean }> = {
  "Vraylar": { label: "Vraylar", generic: "cariprazine hcl" },
  "Dupixent": { label: "Dupixent", generic: "dupilumab" },
  "Rinvoq": { label: "Rinvoq", generic: "upadacitinib" },
  "Jardiance": { label: "Jardiance", generic: "empagliflozin" },
  "Mounjaro": { label: "Mounjaro", generic: "tirzepatide" },
  "Skyrizi": { label: "Skyrizi", generic: "risankizumab-rzaa" },
  "Rexulti": { label: "Rexulti", generic: "brexpiprazole" },
  "Ozempic": { label: "Ozempic", generic: "semaglutide" },
  "Tremfya": { label: "Tremfya", generic: "guselkumab" },
  "Ubrelvy": { label: "Ubrelvy", generic: "ubrogepant" },
  "Qulipta": { label: "Qulipta", generic: "atogepant" },
  "Airsupra": { label: "Airsupra", generic: "albuterol sulfate/budesonide" },
  "Nurtec": { label: "Nurtec", generic: "rimegepant sulfate" },
  "Trelegy": { label: "Trelegy", generic: "fluticasone/umeclidin/vilanter" },
  "Otezla": { label: "Otezla", generic: "apremilast" },
  "Farxiga": { label: "Farxiga", generic: "dapagliflozin propanediol" },
  "Caplyta": { label: "Caplyta", generic: "lumateperone tosylate" },
  "Eliquis": { label: "Eliquis", generic: "apixaban" },
  "Wegovy": { label: "Wegovy", generic: "semaglutide" },
  "Botox": { label: "Botox", generic: "onabotulinumtoxina" },
  "Kerendia": { label: "Kerendia", generic: "finerenone" },
  "Xifaxan": { label: "Xifaxan", generic: "rifaximin" },
  "Veozah": { label: "Veozah", generic: "fezolinetant" },
  "Ingrezza": { label: "Ingrezza", generic: "valbenazine tosylate" },
  "Rybelsus": { label: "Rybelsus", generic: "semaglutide" },
  "Voquezna": { label: "Voquezna", generic: "vonoprazan fumarate" },
  "Austedo": { label: "Austedo", generic: "deutetrabenazine" },
  "Cosentyx": { label: "Cosentyx", generic: "secukinumab" },
  "Xarelto": { label: "Xarelto", generic: "rivaroxaban" },
  "Repatha": { label: "Repatha", generic: "evolocumab" },
  "Breztri": { label: "Breztri", generic: "budesonide/glycopyr/formoterol" },
  "Evenity": { label: "Evenity", generic: "romosozumab-aqqg" },
  "Linzess": { label: "Linzess", generic: "linaclotide" },
  "Auvelity": { label: "Auvelity", generic: "dextromethorphan hbr/bupropion" },
  "Taltz": { label: "Taltz", generic: "ixekizumab" },
  "Entresto": { label: "Entresto", generic: "sacubitril/valsartan" },
  "Nucala": { label: "Nucala", generic: "mepolizumab" },
  "Aristada": { label: "Aristada", generic: "aripiprazole lauroxil" },
  "Gemtesa": { label: "Gemtesa", generic: "vibegron" },
  "Zoryve": { label: "Zoryve", generic: "roflumilast" },
  "Opzelura": { label: "Opzelura", generic: "ruxolitinib phosphate" },
  "Creon": { label: "Creon", generic: "lipase/protease/amylase" },
  "Abilify": { label: "Abilify", generic: "aripiprazole" },
  "Tezspire": { label: "Tezspire", generic: "tezepelumab-ekko" },
  "Spravato": { label: "Spravato", generic: "esketamine hcl" },
  "Xeljanz": { label: "Xeljanz", generic: "tofacitinib citrate" },
  "Stelara": { label: "Stelara", generic: "ustekinumab" },
  "Invega": { label: "Invega", generic: "paliperidone palmitate" },
  "Uzedy": { label: "Uzedy", generic: "risperidone" },
  "Metformin": { label: "Metformin", generic: "generic — control (no payments)", control: true },
};

export const DATA_YEAR = 2024; // program year currently loaded
